// <auto-generated />
using System;
using EFC01.Lib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC01.Lib.Migrations
{
    [DbContext(typeof(EFC01DBContext))]
    [Migration("20251020111612_ErsteMigration")]
    partial class ErsteMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFC01.Lib.Models.Abteilung", b =>
                {
                    b.Property<int>("AbteilungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbteilungId"));

                    b.Property<string>("Abteilungsbezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbteilungId");

                    b.ToTable("AbteilungListe");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Funktion", b =>
                {
                    b.Property<int>("FunktionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FunktionId"));

                    b.Property<string>("Funktionsbezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FunktionId");

                    b.ToTable("FunktionListe");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("MitarbeiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MitarbeiterId"));

                    b.Property<int?>("AbteilungId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Datumaustritt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Datumeintritt")
                        .HasColumnType("date");

                    b.Property<string>("Durchwahl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Extern")
                        .HasColumnType("bit");

                    b.Property<int?>("FunktionId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Geburtsdatum")
                        .HasColumnType("date");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NiederlassungId")
                        .HasColumnType("int");

                    b.Property<string>("Prsnr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MitarbeiterId");

                    b.HasIndex("AbteilungId");

                    b.HasIndex("FunktionId");

                    b.HasIndex("NiederlassungId");

                    b.ToTable("MitarbeiterListe");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Niederlassung", b =>
                {
                    b.Property<int>("NiederlassungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NiederlassungId"));

                    b.Property<string>("Niederlassungsbezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Niederlassungsvorwahl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NiederlassungId");

                    b.ToTable("NiederlassungListe");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Mitarbeiter", b =>
                {
                    b.HasOne("EFC01.Lib.Models.Abteilung", "Abteilung")
                        .WithMany("MitarbeiterListe")
                        .HasForeignKey("AbteilungId");

                    b.HasOne("EFC01.Lib.Models.Funktion", "Funktion")
                        .WithMany("MitarbeiterListe")
                        .HasForeignKey("FunktionId");

                    b.HasOne("EFC01.Lib.Models.Niederlassung", "Niederlassung")
                        .WithMany("MitarbeiterListe")
                        .HasForeignKey("NiederlassungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abteilung");

                    b.Navigation("Funktion");

                    b.Navigation("Niederlassung");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Abteilung", b =>
                {
                    b.Navigation("MitarbeiterListe");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Funktion", b =>
                {
                    b.Navigation("MitarbeiterListe");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Niederlassung", b =>
                {
                    b.Navigation("MitarbeiterListe");
                });
#pragma warning restore 612, 618
        }
    }
}
