// <auto-generated />
using System;
using EFC01.Lib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC01.Lib.Migrations
{
    [DbContext(typeof(EFC01DBContext))]
    partial class EFC01DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFC01.Lib.Models.Abteilung", b =>
                {
                    b.Property<int>("AbteilungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbteilungId"));

                    b.Property<string>("Abteilungsbezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AbteilungId");

                    b.HasIndex("Abteilungsbezeichnung")
                        .IsUnique();

                    b.ToTable("abteilung", "dbo");

                    b.HasData(
                        new
                        {
                            AbteilungId = 1,
                            Abteilungsbezeichnung = "Geschäftsleitung/RW"
                        },
                        new
                        {
                            AbteilungId = 2,
                            Abteilungsbezeichnung = "Infrastruktur"
                        },
                        new
                        {
                            AbteilungId = 3,
                            Abteilungsbezeichnung = "Marketing"
                        },
                        new
                        {
                            AbteilungId = 4,
                            Abteilungsbezeichnung = "Produktion"
                        },
                        new
                        {
                            AbteilungId = 5,
                            Abteilungsbezeichnung = "Vertrieb"
                        });
                });

            modelBuilder.Entity("EFC01.Lib.Models.Funktion", b =>
                {
                    b.Property<int>("FunktionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FunktionId"));

                    b.Property<string>("Funktionsbezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FunktionId");

                    b.HasIndex("Funktionsbezeichnung")
                        .IsUnique();

                    b.ToTable("funktion", "dbo");

                    b.HasData(
                        new
                        {
                            FunktionId = 1,
                            Funktionsbezeichnung = "Berater/in"
                        },
                        new
                        {
                            FunktionId = 2,
                            Funktionsbezeichnung = "Bereichsleiter/in"
                        },
                        new
                        {
                            FunktionId = 3,
                            Funktionsbezeichnung = "Entwickler/in"
                        },
                        new
                        {
                            FunktionId = 4,
                            Funktionsbezeichnung = "Freie/r Mitarbeiter/in"
                        },
                        new
                        {
                            FunktionId = 5,
                            Funktionsbezeichnung = "Geschäftsführer/in"
                        },
                        new
                        {
                            FunktionId = 6,
                            Funktionsbezeichnung = "Mitarbeiter/in"
                        },
                        new
                        {
                            FunktionId = 7,
                            Funktionsbezeichnung = "Projektleiter/in"
                        });
                });

            modelBuilder.Entity("EFC01.Lib.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("MitarbeiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MitarbeiterId"));

                    b.Property<int?>("AbteilungId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DatumAustritt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DatumEintritt")
                        .HasColumnType("date");

                    b.Property<string>("Durchwahl")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Extern")
                        .HasColumnType("bit");

                    b.Property<int?>("FunktionId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Geburtsdatum")
                        .HasColumnType("date");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NiederlassungId")
                        .HasColumnType("int");

                    b.Property<string>("Prsnr")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MitarbeiterId");

                    b.HasIndex("AbteilungId");

                    b.HasIndex("FunktionId");

                    b.HasIndex("NiederlassungId");

                    b.HasIndex("Prsnr")
                        .IsUnique();

                    b.ToTable("mitarbeiter", "dbo");

                    b.HasData(
                        new
                        {
                            MitarbeiterId = 1,
                            AbteilungId = 1,
                            DatumEintritt = new DateOnly(2006, 1, 1),
                            Durchwahl = "20",
                            Email = "gpaul@projektdb.de",
                            Extern = false,
                            FunktionId = 5,
                            Geburtsdatum = new DateOnly(1993, 8, 23),
                            Geschlecht = "w",
                            Nachname = "Paul",
                            NiederlassungId = 3,
                            Prsnr = "1001",
                            Vorname = "Gabriele"
                        },
                        new
                        {
                            MitarbeiterId = 2,
                            AbteilungId = 1,
                            DatumEintritt = new DateOnly(2012, 5, 15),
                            Durchwahl = "22",
                            Email = "kunterlauf@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1970, 2, 6),
                            Geschlecht = "w",
                            Nachname = "Unterlauf",
                            NiederlassungId = 3,
                            Prsnr = "1002",
                            Vorname = "Karin"
                        },
                        new
                        {
                            MitarbeiterId = 3,
                            AbteilungId = 1,
                            DatumEintritt = new DateOnly(2010, 10, 1),
                            Durchwahl = "21",
                            Email = "eschiefner@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1980, 5, 14),
                            Geschlecht = "w",
                            Nachname = "Schiefner",
                            NiederlassungId = 3,
                            Prsnr = "1003",
                            Vorname = "Emi"
                        },
                        new
                        {
                            MitarbeiterId = 4,
                            AbteilungId = 2,
                            DatumEintritt = new DateOnly(2010, 10, 15),
                            Durchwahl = "4567",
                            Email = "ogeist@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1979, 5, 13),
                            Geschlecht = "m",
                            Nachname = "Geist",
                            NiederlassungId = 2,
                            Prsnr = "1004",
                            Vorname = "Ottmar"
                        },
                        new
                        {
                            MitarbeiterId = 5,
                            AbteilungId = 2,
                            DatumEintritt = new DateOnly(2006, 1, 2),
                            Durchwahl = "123",
                            Email = "hwendisch@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1981, 5, 14),
                            Geschlecht = "m",
                            Nachname = "Wendisch",
                            NiederlassungId = 1,
                            Prsnr = "1005",
                            Vorname = "Horst"
                        },
                        new
                        {
                            MitarbeiterId = 6,
                            AbteilungId = 2,
                            DatumEintritt = new DateOnly(2006, 1, 3),
                            Durchwahl = "13",
                            Email = "gkoritz@projektdb.de",
                            Extern = false,
                            FunktionId = 5,
                            Geburtsdatum = new DateOnly(1985, 6, 16),
                            Geschlecht = "w",
                            Nachname = "Koritz",
                            NiederlassungId = 3,
                            Prsnr = "1006",
                            Vorname = "Gundula"
                        },
                        new
                        {
                            MitarbeiterId = 7,
                            AbteilungId = 3,
                            DatumEintritt = new DateOnly(2006, 1, 17),
                            Durchwahl = "35",
                            Email = "klorenz@projektdb.de",
                            Extern = false,
                            FunktionId = 2,
                            Geburtsdatum = new DateOnly(1998, 10, 26),
                            Geschlecht = "w",
                            Nachname = "Lorenz",
                            NiederlassungId = 3,
                            Prsnr = "1007",
                            Vorname = "Kathrin"
                        },
                        new
                        {
                            MitarbeiterId = 8,
                            AbteilungId = 3,
                            DatumEintritt = new DateOnly(2006, 1, 18),
                            Durchwahl = "36",
                            Email = "amuehle@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1971, 3, 8),
                            Geschlecht = "m",
                            Nachname = "Mühle",
                            NiederlassungId = 3,
                            Prsnr = "1008",
                            Vorname = "Andreas"
                        },
                        new
                        {
                            MitarbeiterId = 9,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2006, 1, 1),
                            Durchwahl = "234",
                            Email = "sarendt@projektdb.de",
                            Extern = false,
                            FunktionId = 2,
                            Geburtsdatum = new DateOnly(1986, 7, 18),
                            Geschlecht = "w",
                            Nachname = "Arendt",
                            NiederlassungId = 1,
                            Prsnr = "1009",
                            Vorname = "Sibylle"
                        },
                        new
                        {
                            MitarbeiterId = 10,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2020, 1, 1),
                            Durchwahl = "30",
                            Email = "oheinrich@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1979, 5, 13),
                            Geschlecht = "m",
                            Nachname = "Heinrich",
                            NiederlassungId = 4,
                            Prsnr = "1010",
                            Vorname = "Otto"
                        },
                        new
                        {
                            MitarbeiterId = 11,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2006, 1, 1),
                            Durchwahl = "12",
                            Email = "hrostig@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1993, 8, 23),
                            Geschlecht = "w",
                            Nachname = "Rostig",
                            Prsnr = "1011",
                            Vorname = "Heidi"
                        },
                        new
                        {
                            MitarbeiterId = 12,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2006, 1, 4),
                            Durchwahl = "",
                            Email = "fgasch@projektdb.de",
                            Extern = false,
                            FunktionId = 4,
                            Geburtsdatum = new DateOnly(1979, 3, 15),
                            Geschlecht = "m",
                            Nachname = "Gasch",
                            Prsnr = "1012",
                            Vorname = "Fritz"
                        },
                        new
                        {
                            MitarbeiterId = 13,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2015, 10, 1),
                            Durchwahl = "232",
                            Email = "mschulze@projektdb.de",
                            Extern = true,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1969, 2, 6),
                            Geschlecht = "m",
                            Nachname = "Schulze",
                            Prsnr = "1013",
                            Vorname = "Mathias"
                        },
                        new
                        {
                            MitarbeiterId = 14,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2015, 10, 1),
                            Durchwahl = "4566",
                            Email = "boehme@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1996, 9, 24),
                            Geschlecht = "m",
                            Nachname = "Oehme",
                            Prsnr = "1014",
                            Vorname = "Ben"
                        },
                        new
                        {
                            MitarbeiterId = 15,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2018, 10, 1),
                            Durchwahl = "4568",
                            Email = "kvettin@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1969, 2, 5),
                            Geschlecht = "m",
                            Nachname = "Vettin",
                            Prsnr = "1015",
                            Vorname = "Konstantin"
                        },
                        new
                        {
                            MitarbeiterId = 16,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2018, 1, 13),
                            Durchwahl = "20",
                            Email = "akayser@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1968, 2, 5),
                            Geschlecht = "m",
                            Nachname = "Kayser",
                            Prsnr = "1016",
                            Vorname = "Adel"
                        },
                        new
                        {
                            MitarbeiterId = 17,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2006, 1, 14),
                            Durchwahl = "4567",
                            Email = "agorochow@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(2002, 11, 28),
                            Geschlecht = "m",
                            Nachname = "Gorochow",
                            Prsnr = "1017",
                            Vorname = "Alexander"
                        },
                        new
                        {
                            MitarbeiterId = 18,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2006, 1, 15),
                            Durchwahl = "40",
                            Email = "joreilley@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(2000, 10, 27),
                            Geschlecht = "m",
                            Nachname = "O'Reilly",
                            Prsnr = "1018",
                            Vorname = "John"
                        },
                        new
                        {
                            MitarbeiterId = 19,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2016, 1, 16),
                            Durchwahl = "233",
                            Email = "mkasischke@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(2002, 11, 28),
                            Geschlecht = "w",
                            Nachname = "Kasischke",
                            Prsnr = "1019",
                            Vorname = "Mandy"
                        },
                        new
                        {
                            MitarbeiterId = 20,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2011, 1, 19),
                            Durchwahl = "4569",
                            Email = "mozuen@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1981, 5, 14),
                            Geschlecht = "m",
                            Nachname = "Ozün",
                            Prsnr = "1020",
                            Vorname = "Mehmet"
                        },
                        new
                        {
                            MitarbeiterId = 21,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2006, 1, 20),
                            Durchwahl = "50",
                            Email = "sboerner@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1989, 7, 20),
                            Geschlecht = "w",
                            Nachname = "Kaykin",
                            Prsnr = "1021",
                            Vorname = "Zylfiye"
                        },
                        new
                        {
                            MitarbeiterId = 22,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2006, 1, 21),
                            Durchwahl = "4570",
                            Email = "pfuehr@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1989, 7, 20),
                            Geschlecht = "m",
                            Nachname = "Führ",
                            Prsnr = "1022",
                            Vorname = "Paul"
                        },
                        new
                        {
                            MitarbeiterId = 23,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2006, 1, 22),
                            Durchwahl = "4571",
                            Email = "krossberg@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(2002, 11, 28),
                            Geschlecht = "w",
                            Nachname = "Roßberg",
                            Prsnr = "1023",
                            Vorname = "Katja"
                        },
                        new
                        {
                            MitarbeiterId = 24,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2010, 10, 1),
                            Durchwahl = "234",
                            Email = "jcernij@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1976, 4, 11),
                            Geschlecht = "m",
                            Nachname = "Cernij",
                            Prsnr = "1024",
                            Vorname = "Juri"
                        },
                        new
                        {
                            MitarbeiterId = 25,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2022, 10, 1),
                            Durchwahl = "4572",
                            Email = "gfeluscini@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(2004, 11, 29),
                            Geschlecht = "m",
                            Nachname = "Feluscini",
                            Prsnr = "1025",
                            Vorname = "Giovanni"
                        },
                        new
                        {
                            MitarbeiterId = 26,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2009, 10, 1),
                            Durchwahl = "14",
                            Email = "molzychovski@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1980, 12, 4),
                            Geschlecht = "m",
                            Nachname = "Olzychovski",
                            Prsnr = "1026",
                            Vorname = "Marek"
                        },
                        new
                        {
                            MitarbeiterId = 27,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2010, 10, 1),
                            Durchwahl = "15",
                            Email = "ffleurol@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1995, 9, 23),
                            Geschlecht = "m",
                            Nachname = "Fleurol",
                            Prsnr = "1027",
                            Vorname = "Francois"
                        },
                        new
                        {
                            MitarbeiterId = 28,
                            AbteilungId = 4,
                            DatumEintritt = new DateOnly(2010, 10, 1),
                            Durchwahl = "16",
                            Email = "kpiskun@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1966, 1, 4),
                            Geschlecht = "m",
                            Nachname = "Piskun",
                            Prsnr = "1028",
                            Vorname = "Konstantin"
                        },
                        new
                        {
                            MitarbeiterId = 29,
                            AbteilungId = 5,
                            DatumEintritt = new DateOnly(2006, 1, 1),
                            Durchwahl = "",
                            Email = "heinz@haase.de",
                            Extern = true,
                            FunktionId = 4,
                            Geburtsdatum = new DateOnly(2001, 11, 27),
                            Geschlecht = "m",
                            Nachname = "Haase",
                            Prsnr = "1029",
                            Vorname = "Heinz"
                        },
                        new
                        {
                            MitarbeiterId = 30,
                            AbteilungId = 5,
                            DatumEintritt = new DateOnly(2006, 1, 1),
                            Durchwahl = "33",
                            Email = "gthurow@projektdb.de",
                            Extern = true,
                            FunktionId = 4,
                            Geburtsdatum = new DateOnly(1991, 8, 21),
                            Geschlecht = "m",
                            Nachname = "Thurow",
                            Prsnr = "1030",
                            Vorname = "Gerald"
                        },
                        new
                        {
                            MitarbeiterId = 31,
                            AbteilungId = 5,
                            DatumEintritt = new DateOnly(2010, 10, 1),
                            Durchwahl = "124",
                            Email = "sfischer@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1979, 5, 13),
                            Geschlecht = "w",
                            Nachname = "Fischer",
                            Prsnr = "1031",
                            Vorname = "Sonja"
                        },
                        new
                        {
                            MitarbeiterId = 32,
                            AbteilungId = 5,
                            DatumEintritt = new DateOnly(2010, 10, 1),
                            Durchwahl = "10",
                            Email = "hschwienke@projektdb.de",
                            Extern = false,
                            FunktionId = 6,
                            Geburtsdatum = new DateOnly(1974, 3, 9),
                            Geschlecht = "w",
                            Nachname = "Schwienke",
                            Prsnr = "1032",
                            Vorname = "Hildegard"
                        },
                        new
                        {
                            MitarbeiterId = 33,
                            AbteilungId = 5,
                            DatumEintritt = new DateOnly(2010, 10, 1),
                            Durchwahl = "34",
                            Email = "eoltenbuerstel@projektdb.de",
                            Extern = false,
                            FunktionId = 2,
                            Geburtsdatum = new DateOnly(1964, 1, 2),
                            Geschlecht = "m",
                            Nachname = "Oltenbürstel",
                            Prsnr = "1033",
                            Vorname = "Erich"
                        });
                });

            modelBuilder.Entity("EFC01.Lib.Models.Niederlassung", b =>
                {
                    b.Property<int>("NiederlassungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NiederlassungId"));

                    b.Property<string>("Niederlassungsbezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Niederlassungsvorwahl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NiederlassungId");

                    b.HasIndex("Niederlassungsbezeichnung")
                        .IsUnique();

                    b.ToTable("niederlassung", "dbo");

                    b.HasData(
                        new
                        {
                            NiederlassungId = 1,
                            Niederlassungsbezeichnung = "Berlin",
                            Niederlassungsvorwahl = "(030) 65756"
                        },
                        new
                        {
                            NiederlassungId = 2,
                            Niederlassungsbezeichnung = "Frankfurt",
                            Niederlassungsvorwahl = "(060) 345012"
                        },
                        new
                        {
                            NiederlassungId = 3,
                            Niederlassungsbezeichnung = "Hamburg",
                            Niederlassungsvorwahl = "(040) 1234"
                        },
                        new
                        {
                            NiederlassungId = 4,
                            Niederlassungsbezeichnung = "München",
                            Niederlassungsvorwahl = "(089) 54398"
                        });
                });

            modelBuilder.Entity("EFC01.Lib.Models.Mitarbeiter", b =>
                {
                    b.HasOne("EFC01.Lib.Models.Abteilung", "Abteilung")
                        .WithMany("MitarbeiterListe")
                        .HasForeignKey("AbteilungId");

                    b.HasOne("EFC01.Lib.Models.Funktion", "Funktion")
                        .WithMany("MitarbeiterListe")
                        .HasForeignKey("FunktionId");

                    b.HasOne("EFC01.Lib.Models.Niederlassung", "Niederlassung")
                        .WithMany("MitarbeiterListe")
                        .HasForeignKey("NiederlassungId");

                    b.Navigation("Abteilung");

                    b.Navigation("Funktion");

                    b.Navigation("Niederlassung");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Abteilung", b =>
                {
                    b.Navigation("MitarbeiterListe");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Funktion", b =>
                {
                    b.Navigation("MitarbeiterListe");
                });

            modelBuilder.Entity("EFC01.Lib.Models.Niederlassung", b =>
                {
                    b.Navigation("MitarbeiterListe");
                });
#pragma warning restore 612, 618
        }
    }
}
