// <auto-generated />
using System;
using EFC04.Lib.Models.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC04.Lib.Migrations.EFC04_JSONDB
{
    [DbContext(typeof(EFC04_JSONDBContext))]
    partial class EFC04_JSONDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFC04.Lib.Models.Json.Kunde", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundeId"));

                    b.Property<DateOnly?>("Geburtsdatum")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<string>("Geschlecht")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateOnly?>("Kundeseit")
                        .HasPrecision(0)
                        .HasColumnType("date");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vorname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KundeId");

                    b.ToTable("Kunde", "json");
                });

            modelBuilder.Entity("EFC04.Lib.Models.Json.Kunde", b =>
                {
                    b.OwnsOne("EFC04.Lib.Models.Json.KundeDetails", "Kundedetails", b1 =>
                        {
                            b1.Property<int>("KundeId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Telefon")
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("varchar(20)");

                            b1.HasKey("KundeId");

                            b1.ToTable("Kunde", "json");

                            b1.ToJson("Kundedetails");

                            b1.WithOwner()
                                .HasForeignKey("KundeId");

                            b1.OwnsOne("EFC04.Lib.Models.Json.Adresse", "Anschrift", b2 =>
                                {
                                    b2.Property<int>("KundeDetailsKundeId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Hausnummer")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)");

                                    b2.Property<string>("Land")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("Ort")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("Plz")
                                        .HasMaxLength(10)
                                        .IsUnicode(false)
                                        .HasColumnType("varchar(10)");

                                    b2.Property<string>("Strasse")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.HasKey("KundeDetailsKundeId");

                                    b2.ToTable("Kunde", "json");

                                    b2.WithOwner()
                                        .HasForeignKey("KundeDetailsKundeId");
                                });

                            b1.Navigation("Anschrift");
                        });

                    b.Navigation("Kundedetails");
                });
#pragma warning restore 612, 618
        }
    }
}
