//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20.10.2025 10:21:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ADOTEST.Lib.Models
{
    public partial class Mitarbeiter {

        public Mitarbeiter()
        {
            this.Extern = false;
            OnCreated();
        }

        public int MitarbeiterId { get; set; }

        public string Prsnr { get; set; }

        public string Nachname { get; set; }

        public string Vorname { get; set; }

        public string Geschlecht { get; set; }

        public DateOnly Datumeintritt { get; set; }

        public DateOnly? Datumaustritt { get; set; }

        public bool? Extern { get; set; }

        public string Email { get; set; }

        public string Durchwahl { get; set; }

        public int? AbteilungId { get; set; }

        public int? FunktionId { get; set; }

        public DateOnly? Geburtsdatum { get; set; }

        public int NiederlassungId { get; set; }


        public virtual Funktion Funktion { get; set; }


        public virtual Abteilung Abteilung { get; set; }


        public virtual Niederlassung Niederlassung { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
