//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20.10.2025 10:21:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ADOTEST.Lib.Models
{
    public partial class Niederlassung {

        public Niederlassung()
        {
            this.MitarbeiterListe = new List<Mitarbeiter>();
            OnCreated();
        }

        public int NiederlassungId { get; set; }

        public string Niederlassungsbezeichnung { get; set; }

        public string Niederlassungsvorwahl { get; set; }


        public virtual IList<Mitarbeiter> MitarbeiterListe { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
