//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20.10.2025 10:21:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace EFC02.Lib.Models
{
    [Table("abteilung",Schema ="dbo")]
    [Index(nameof(Abteilungsbezeichnung), IsUnique = true)] //bestimmt, dass der Inhalt der angegebenen Spalte nur einmalig vorkommen kann
    public partial class Abteilung {

        public Abteilung()
        {
            this.MitarbeiterListe = new List<Mitarbeiter>();
            OnCreated();
        }

        [Key]
        public int AbteilungId { get; set; }

        [Required]
        [StringLength(50)]
        public string Abteilungsbezeichnung { get; set; }


        public virtual IList<Mitarbeiter> MitarbeiterListe { get; set; } // = new List<Mitarbeiter>(); 

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
